[command]
# Preprocess the orographic formdrag- why does this need to be in the
# suite? It doesn't appear to be dependent on the grid or the other
# ancillaries.
default = python ancil_orographic_formdrag_preproc.py \
	= ${OROGRAPHY_SOURCE} -o=${OUTPUT}

[env]
# Source data to use for orography
OROGRAPHY_SOURCE=${ANCIL_MASTER}/atmos/master/ash/GLOBE/v1/qrparm.ash

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/orography/orog_formdrag_preproc.ash.nc
