[command]
# Creates basic initial soil conditions. The MODEL_SOIL_DEPTHS are assigned in
# flow.cylc depending on the choice of model. It can be overridden by supplying
# that environment variable here, as a comma separated list of depths, representing
# the centre of each soil layer.
default = python functional-soil-initial-conditions.py --target-lsm=${TARGET_LSM} \
        = --soil-depths=${MODEL_SOIL_DEPTHS} --soil-parameters=${SOIL_PARAMETERS} \
	= --output=${OUTPUT}

[env]
# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/soil/initial_conditions

# Location for the soil parameters file- must contain 
