[command]
# Regrids the source LAI dataset onto the target landmask.
default = python ancil_lai.py ${LAI_SOURCE} \
	= --target-lsm=${TARGET_LSM} -o=${OUTPUT}

[env]
# Source for the LAI on the target grid
LAI_SOURCE=${ANCIL_TARGET_PATH}/regridded/regridded_lai.nc

# Set of weights used to map the LAI onto PFTs. This by default points
# to either the CABLE or JULES weights- modify it to use a custom set of
# weights
RELATIVE_WEIGHTS=${DEFAULT_WEIGHTS}

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/vegetation/lai
