[command]
# Regrids the source LAI dataset onto the target landmask.
default = python ancil_lai.py ${LAI_SOURCE} ${LAND_COVER} \
        = --relative-weights=${RELATIVE_WEIGHTS} \
        = -o=${OUTPUT} --ants-config=${ANTS_CONFIG}

[env]
# Source for the LAI on the target grid
LAI_SOURCE=${ANCIL_TARGET_PATH}/regridded/regridded_lai.nc

# Source for the land cover types
LAND_COVER=${ANCIL_TARGET_PATH}/vegetation/qrparm.veg.frac_cci.nc

# Set of weights used to map the LAI onto PFTs. This by default points
# to either the CABLE or JULES weights- modify it to use a custom set of
# weights
RELATIVE_WEIGHTS=${DEFAULT_WEIGHTS}

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/vegetation/lai

# App configuration
ANTS_CONFIG=${PWD}/rose-app-run.conf

[ants_decomposition]
x_split=10
y_split=10

[ants_regridding_horizontal]
scheme=Linear
