[command]
# Compute the mean orography. See the app for descriptions of the
# configuration options.
default = python ancil_orography_mean.py ${OROGRAPHY_SOURCE} \
	= --target-lsm=${TARGET_LSM} --blend-orography \
	= --max-slope=${MAX_SLOPE} --max-smooth=${MAX_SMOOTH} \
	= -o=${OUTPUT} --ants-config=${ANTS_CONFIG}

[env]
# Source for the orography data
OROGRAPHY_SOURCE=${ANCIL_MASTER}/atmos/master/orography/GMTED_RAMP2/v2/qrparm.orog

# Landmask to project onto, from ancil_lct

# Orography smoothing parameters
MAX_SLOPE=0.02
MAX_SMOOTH=1

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/orography/qrparm.orog_mean_tmp

# App configuration
ANTS_CONFIG=${PWD}/rose-app-run.conf

[ants_decomposition]
x_split=10
y_split=10

[ants_regridding_horizontal]
scheme=TwoStage
