[command]
# The MODEL_TREE_IDS are set in flow.cylc based on the specified LAND_MODEL
default = python ancil_canopy_heights.py ${LAI_SOURCE} \
	    = --trees-dataset=${TREE_HEIGHT_SOURCE} \
	    = --canopy-height-factors=${HEIGHT_FACTORS} --tree-ids=${MODEL_TREE_TILES} \
	    = --max-search-dist=${MAX_SEARCH_DIST} \
        = -o=${OUTPUT} --ants-config=${ANTS_CONFIG} --netcdf-only

[env]
# Source for the LAI data
LAI_SOURCE=${ANCIL_TARGET_PATH}/preproc/lai.nc

# Source for the tree heights
TREE_HEIGHT_SOURCE=${ANCIL_MASTER}/atmos/master/vegetation/canopy/simard/v1/Simard_Pinto_3DGlobalVeg_JGR.nc

# Mapping from the LAI to canopy heights- modify this to use your own
# set of factors
HEIGHT_FACTORS=${DEFAULT_HEIGHT_FACTORS}

# What's the maximum distance in km to search for valid canopy height data e.g. for islands
MAX_SEARCH_DIST=500

# Where to write the output to
OUTPUT=${ANCIL_TARGET_PATH}/preproc/canopy_heights

# App configuration
ANTS_CONFIG=${PWD}/rose-app-run.conf

[ants_decomposition]
x_split=2
y_split=2

[ants_regridding_horizontal]
scheme=TwoStage
