# Suite level variables are set here, while app level configuration are
# set in the respective apps. There is not a clear delineation between
# suite level and app level variables- it is loosely based on whether the
# option affects multiple apps, but this is not a hard and fast rule.
#
# For example, technically the choice of "grid_type" and "grid_definition"
# only affect the "ancil_lct" app, which then has downstream effects, but it 
# "feels" like a suite level choice. But the orography smoothing parameters
# for "ancil_orography_mean" similarly have downstream effects, but they are
# treated as app level configurations. The location of an option is decided with
# a judgement call based on how likely it is for a user to modify the option,
# and how "global" its effect is.
#
# In short, the user should not have to modify anything outside of this file,
# or the respective apps' "rose-app.conf" (unless running on different machines).

[template variables]
# Project that the suite will be installed and run under. Working directory will be
# /scratch/${STORAGE_PROJECT}/${USER}/cylc-run/CCI-Ancillary-Suite.
STORAGE_PROJECT="rp23"

# Project that the job will be run under.
COMPUTE_PROJECT="rp23"

# Which land model to target.
# Valid options: "CABLE", "JULES"
LAND_MODEL="CABLE"

# Whether to use a grid definition and allow the land cover to
# determine to ocean, or use a reference mask.
# Valid options: "land_cover", "land_sea_mask", "ocean_mesh".
GRID_SOURCE="ocean_mesh"

# Either the source grid definition namelist, existing landseamask to use, or ocean mesh,
# depending on the GRID_SOURCE option.
# Must be an existing file.
GRID_FILE="/scratch/rp23/lw5085/access-om3-025deg-ESMFmesh.nc"
#GRID_FILE="/g/data/access/TIDS/UM/ancil/data/namelist/grids/grid.n96e/latest/grid.n96e"

# Which resolution to use
RESOLUTION="n96e"
# The vertical discretization for atmosphere ancillaries. Should be a namelist
# in the UM vertical discretization format.
# Must be an existing file
VERTICAL_DISCRETIZATION="/g/data/access/TIDS/UM/ancil/data/namelist/vertical/vert_85/latest/vert_85"

# Calendar to use for the temporal ancillaries.
# Valid options: "360day", "gregorian"
CALENDAR="360day"

# Which year to use for the CCI land cover
CCI_YEAR=2015
