[command]
# The MODEL_C3_GRASS_TILE and MODEL_C4_GRASS_TILE are set in flow.cylc,
# based on the specified land model.
default	= python ancil_lct_postproc_c4.py ${VEGETATION_SOURCE} --c4-source=${C4_SOURCE} \
	= --c3level=${MODEL_C3_GRASS_TILE} --c4level=${MODEL_C4_GRASS_TILE} \
	= -o=${OUTPUT} --ants-config=${ANTS_CONFIG}

[env]
# Source land cover fractions from ancil_lct
VEGETATION_SOURCE=${ANCIL_TARGET_PATH}/vegetation/qrparm.veg.frac_cci_pre_c4.nc

# Regridded source for C4 fraction
C4_SOURCE=${ANCIL_TARGET_PATH}/regridded/regridded_c4_fraction.nc

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/vegetation/qrparm.veg.frac_cci

# 
ANTS_CONFIG=${PWD}/rose-app-run.conf

[ants_decomposition]
x_split=4
y_split=4

[ants_regridding_horizontal]
scheme=TwoStage
