[command]
default = python ancil_orographic_wavedrag.py ${OROGRAPHY_SOURCE} \
	= --mean-orography-input=${MEAN_OROGRAPHY_INPUT} \
	= --mean-orography-output=${MEAN_OROGRAPHY_OUTPUT} \
	= -o=${OUTPUT}

[env]
# Source for the filtered orography data, from ancil_orography_filtered_preproc
OROGRAPHY_SOURCE=${ANCIL_TARGET_PATH}/orography/qrparm.orog_filtered_preproc.nc

# Mean orography from ancil_orography_mean
MEAN_OROGRAPHY_INPUT=${ANCIL_TARGET_PATH}/orography/qrparm.orog_mean_tmp.nc

# Further processed mean orography
MEAN_OROGRAPHY_OUTPUT=${ANCIL_TARGET_PATH}/orography/qrparm.mean_orog

# Where to write the final output
OUTPUT=${ANCIL_TARGET_PATH}/orography/qrparm.orog_wavedrag
