[command]
# Preprocess the aerosol climatology. CALENDAR is set in rose-suite.conf
default = python preproc_aeroclim.py --source-root=${AEROCLIM_SOURCE} \
	    = --datasource="${METADATA_SOURCE}" --calendar=${CALENDAR} \
	    = -o=${OUTPUT}
	    =
	    = ncatted -O -h -a update_type,global,o,c,"2" ${OUTPUT}

[env]
# Source for the aerosol climatology
AEROCLIM_SOURCE=${ANCIL_MASTER}/atmos/master/aero_clims/u-ck036/apm.pp

# Metadata required
METADATA_SOURCE="Climatology created from Met Office Unified Model experiment u-ck036 between years 1989 and 2009"

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/preproc/qrclim.pre_aerosols.nc

[file:${ANCIL_TARGET_PATH}/preproc]
mode=mkdir
