[command]
# Fixes the ice fractions around antarctica.
default = python ancil_fix_antarctic_permanent_ice.py \
	= --input=${VEGETATION_SOURCE} --output=${OUTPUT}

[env]
# Source land cover from CCI, post NCAR split
VEGETATION_SOURCE=${ANCIL_TARGET_PATH}/vegetation/qrparm.veg.frac_cci.nc

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/vegetation/qrparm.veg.frac
