[command]
# Creates basic initial soil conditions. The MODEL_SOIL_DEPTHS are assigned in
# flow.cylc depending on the choice of model. It can be overridden by supplying
# that environment variable here, as a comma separated list of depths, representing
# the centre of each soil layer.
# The MOISTURE_UNITS sets whether the moisture units should be 'volumetric' (m3 m-3)
# or 'mass' (kg m-2). Set in flow.cylc, based on the model.
default = python functional-soil-initial-conditions.py \
        = --soil-thickness=${MODEL_SOIL_THICKNESS} --soil-parameters=${SOIL_PARAMETERS} \
	    = --moisture-units={MOISTURE_UNITS} --max-temperature=${MAX_TEMPERATURE} \
        = --output=${OUTPUT}

[env]
# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/soil/initial_conditions

# Location for the soil parameters file- must contains volumetric_soil_mositure_content_at_saturation
SOIL_PARAMETERS=${ANCIL_TARGET_PATH}/soil/qrparm.soil.nc

# Maximum to apply at the equator, linearly tends to 0 at the poles
MAX_TEMPERATURE=25.0

# Can override MODEL_SOIL_THICKNESS and MOISTURE_UNITS here if desired.
