[command]
# Compute the topography from source data
default = python ancil_topographic_index.py ${TOPOGRAPHY_SOURCE} \
	= --lct-ancillary=${LCT_SOURCE} -o=${OUTPUT} --ants-config=${ANTS_CONFIG}
	= --ice-tile-id=${MODEL_ICE_TILE}

[env]
# Source for the topographic index data
TOPOGRAPHY_SOURCE=${ANCIL_PREPROC_PATH}/topographic_index.nc

# Land cover fractions from ancil_lct
LCT_SOURCE=${ANCIL_TARGET_PATH}/vegetation/qrparm.veg.frac

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/soil/qrparm.hydtop

# App configuration
ANTS_CONFIG=${PWD}/rose-app-run.conf

[ants_decomposition]
x_split=10
y_split=10

[ants_regridding_horizontal]
scheme=TwoStage
