[command]
# Regrid the sea ice
default = python ancil_general_regrid.py ${SST_SOURCE} \
	= --target-lsm=${TARGET_LSM} --invert-mask \
	= -o=${OUTPUT}

[env]
# Source for the SST ancillaries- Calendar is set in rose-suite.conf
SST_SOURCE=${ANCIL_MASTER}/atmos/master/sst/reynolds/198909_201912_${CALENDAR}/v1/reynolds_sst.nc

# Target LSM to project onto, from ancil_LCT
TARGET_LSM=${ANCIL_TARGET_PATH}/qrparm.mask.nc

# Where to write the output to
OUTPUT=${ANCIL_TARGET_PATH}/ocean/qrclim.sst
