[command]
# Preproc the river routing- this seems independent of resolution or configuration, should not be in the suite?
default = python ancil_river_routing_preproc.py ${ROUTING_SOURCE} \
	    = -o=${OUTPUT} --netcdf-only --ants-config=${ANTS_CONFIG}

[env]
# Source data for the river routing
ROUTING_SOURCE=${ANCIL_MASTER}/atmos/master/rivers_trip/sequence/etopo5/v1/trip_routing_data.pp

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/preproc/trip_routing_data

# App configuration
ANTS_CONFIG=${PWD}/rose-app-run.conf

[ants_regridding_horizontal]
scheme=Linear
