[command]
# GRID_FILE and RESOLUTION come from the rose_suite.conf
default = python landseamask_from_ocean_mesh.py --ocean-mesh-file=${OCEAN_MESH} \
	    = --output=${OUTPUT} --atm-resolution=${RESOLUTION}

[env]
OUTPUT=${ANCIL_TARGET_PATH}/land_sea_mask

[file:${ANCIL_TARGET_PATH}/land_sea_mask]
mode=mkdir
