[command]
# Create the dimethyl sulphide (DMS) ancillaries
default = python ancil_dms.py ${DMS_SOURCE} \
	= --target-lsm=${TARGET_LSM} -o=${OUTPUT} --ants-config=${ANTS_CONFIG}

[env]
# Source data for the DMS
DMS_SOURCE=${ANCIL_MASTER}/atmos/master/classic_aerosol/DMS/lana/v2/Lana_DMS_ocean_1x1deg.nc

# Target LSM to project onto, from ancil_LCT

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/aerosols/qrclim.sulpdms

# App configuration
ANTS_CONFIG=${PWD}/rose-app-run.conf

[ants_decomposition]
x_split=10
y_split=10

[ants_regridding_horizontal]
scheme=TwoStage
