[command]
# This is an optional pre-processing step, which should only happen a new year of the
# CCI land cover is to be processed.
default = python preprocess_CCI_water.py --CCI-land-cover=${LAND_COVER_SOURCE} \
        = --CCI-water-dir=${WATER_BODIES_SOURCE} --output=${OUTPUT}

[env]
# Which year to target
CCI_YEAR=2015

# Resulting path for the land cover file
LAND_COVER_SOURCE=/g/data/cm45/access-nri/esacci/land_cover_maps/v2.0.7/ESACCI-LC-L4-LCCS-Map-300m-P1Y-${CCI_YEAR}-v2.0.7b.nc

# Source water bodies dataset
WATER_BODIES_SOURCE=/g/data/cm45/access-nri/esacci/water_bodies/v4.0/

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/preproc/ESACCI-LCCS-and-Water-Bodies.nc

[file:${ANCIL_TARGET_PATH}/preproc]
mode=mkdir
