[command]
default = python ancil_general_regrid.py ${C4_SOURCE} --netcdf-only \
	= --target-lsm=${TARGET_LSM} -o=${OUTPUT} --ants-config=${ANTS_CONFIG}

[env]
# Year to use for LULCC data
TARGET_YEAR=2005

# Source for the NCAR Land Use and Land Cover Change data
LULCC_SOURCE=/g/data/access/projects/access/data/lulcc-ncar/pftlandusedyn.0.5x0.5.simyr1850-2005.c090630/mksrf_landuse_rc${TARGET_YEAR}_c090630.nc

# Where to write the regridded fractions to
OUTPUT=${ANCIL_TARGET_PATH}/regridded/NCAR-LULCC

# App configuration
ANTS_CONFIG=${PWD}/rose-app-run.conf

[ants_decomposition]
x_split=5
y_split=5

[ants_regridding_horizontal]
scheme=TwoStage
