[command]
default= python ancil_CMIP_ozone.py --ozone-path=${OZONE_PATH} \
       = --temperature_path=${TEMPERATURE_PATH} --climatological-temperature \
       = --orography-file=${OROGRAPHIC_GRID} --vertical-disc=${VERTICAL_DISCRETIZATION} \
       = --year-range=${START_YEAR},${END_YEAR} --output=${OUTPUT}

[env]

OZONE_PATH=${INPUTS4MIPS_DIR}/CMIP7/CMIP/FZJ/FZJ-CMIP-ozone-2-0/atmos/mon/vmro3/gn/v20260211/vmro3_input4MIPs_ozone_CMIP_FZJ-CMIP-ozone-2-0_gn_*
TEMPERATURE_PATH=${INPUT4MIPS_DIR}/CMIP7/CMIP/FZJ/FZJ-CMIP-ozone-1-2/atmos/monC/zmta/gn/v20251118/zmta_input4MIPs_ozone_CMIP_FZJ-CMIP-ozone-1-2_gn_185001-185012-clim.nc
OROGRAPHIC_GRID=${ANCIL_TARGET_PATH}/orography/qrparm.orog_wavedrag
OUTPUT=${ANCIL_TARGET_PATH}/ozone/qrclim.ozone

[file:${ANCIL_TARGET_PATH}/ozone]
mode=mkdir
