[command]
default=ants-launch python -u ${CYLC_SUITE_DEF_PATH}/app/${CYLC_TASK_NAME}/file/ozone_cmip6_ancillary_for_suite.py \
       =${sources_ozone} -o ${output_root} --tempfile ${sources_temp} --target-grid-orog=${target_grid_orog} --levelfile ${level_file} -b ${start_year} -e ${end_year} --extend_data ${extend_data} --calendar ${calendar} --timeaxis ${timeaxis}

[env]
calendar=${CALENDAR}
end_year=2020
extend_data=False
level_file=${VERTICAL_DISCRETIZATON}
output_root=${ANCIL_TARGET_PATH}/aerosols/
sources_ozone=${INPUTS4MIPS_DIR}/CMIP7/CMIP/FZJ/FZJ-CMIP-ozone-2-0/atmos/mon/vmro3/gn/v20260211/vmro3_input4MIPs_ozone_CMIP_FZJ-CMIP-ozone-2-0_gn_*
sources_temp=${INPUT4MIPS_DIR}/CMIP7/CMIP/FZJ/FZJ-CMIP-ozone-1-2/atmos/monC/zmta/gn/v20251118/zmta_input4MIPs_ozone_CMIP_FZJ-CMIP-ozone-1-2_gn_185001-185012-clim.nc
start_year=1980
target_grid_orog=${ANCIL_TARGET_PATH}/orography/qrparm.orog_wavedrag
timeaxis=Timemean

[file:${ANCIL_TARGET_PATH}/aerosols]
mode=mkdir
