[command]
# The VERTICAL_DISCRETIZATION, START_YEAR and END_YEAR are defined in rose_suite.conf
default= python ancil_CMIP_ozone.py --ozone-path=${OZONE_PATH} \
       = --temperature_path=${TEMPERATURE_PATH} ${CLIMATOLOGICAL_TEMPERATURE} \
       = --orography-file=${OROGRAPHIC_GRID} --vertical-disc=${VERTICAL_DISCRETIZATION} \
       = --year-range=${START_YEAR},${END_YEAR} --output=${OUTPUT}

[env]
# Source for the ozone
OZONE_PATH=${INPUTS4MIPS_DIR}/CMIP7/CMIP/FZJ/FZJ-CMIP-ozone-2-0/atmos/mon/vmro3/gn/v20260211/vmro3_input4MIPs_ozone_CMIP_FZJ-CMIP-ozone-2-0_gn_*

# Source for the temperature (zmta) used to generate model heights
TEMPERATURE_PATH=${INPUT4MIPS_DIR}/CMIP7/CMIP/FZJ/FZJ-CMIP-ozone-1-2/atmos/monC/zmta/gn/v20251118/zmta_input4MIPs_ozone_CMIP_FZJ-CMIP-ozone-1-2_gn_185001-185012-clim.nc

# Orographic grid
OROGRAPHIC_GRID=${ANCIL_TARGET_PATH}/orography/qrparm.orog_wavedrag

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/ozone/qrclim.ozone

# Whether to zonal average the ozone
ZONAL=0

# Whether to assume climatological temperature
CLIMATOLOGICAL_TEMPERATURE=1

# Whether to allow it to extend outside the range of the data
EXTEND=0

[file:${ANCIL_TARGET_PATH}/ozone]
mode=mkdir
