[command]
# Create the ocean colour ancillaries
default = python ancil_general_regrid.py ${SEA_COLOUR_SOURCE} \
	= --target-lsm=${TARGET_LSM} -o=${OUTPUT} --ants-config=${ANTS_CONFIG}

[env]
# Source data for the sea colour
SEA_COLOUR_SOURCE=${ANCIL_MASTER}/atmos/master/sea_clim/GlobColour/v2/qrparm.sea.nc

# Target LSM to project onto, from ancil_LCT

# Where to write the output to
OUTPUT=${ANCIL_TARGET_PATH}/qrclim.sea

# App configuration
ANTS_CONFIG=${PWD}/rose-app-run.conf

[ants_decomposition]
x_split=10
y_split=10

[ants_regridding_horizontal]
scheme=Linear
