[command]
# Merge the LAI and canopy heights into a single vegetation ancillary
default = python ancil_2anc.py ${LAI_SOURCE} ${CANOPY_HEIGHTS_SOURCE} \
	    = -o=${OUTPUT}

[env]
# Source for the generated LAI data
LAI_SOURCE=${ANCIL_TARGET_PATH}/vegetation/lai.nc

# Source for the generated canopy heights data
CANOPY_HEIGHTS_SOURCE=${ANCIL_TARGET_PATH}/vegetation/canopy_heights.nc

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/vegetation/qrparm.veg.func
