[command]
# Create the river routing ancillary file. The script says that -make_nemo_rivers is necessary, but it doesn't seem like the nemo rivers are used at all in AM3?
default = python ancil_river_routing.py ${ROUTING_SOURCE} \
	    = --land-cover-fraction=${LANDFRAC} --land_threshold_outflow=0.5 \
	    = --ocean_runoff_file=${RUNOFF_SOURCE} --orca_dom_file=${ORCA_DOMAIN} \
	    = -o=${OUTPUT} --ants-config=${ANTS_CONFIG}

[env]
# Source data for river routing source, from ancil_river_routing_preproc
ROUTING_SOURCE=${ANCIL_TARGET_PATH}/preproc/trip_routing_data.nc

# The land fractions, from ancil_LCT
LANDFRAC=${ANCIL_TARGET_PATH}/land_sea_mask/qrparm.landfrac

# Source data for the runoff
RUNOFF_SOURCE=/g/data/access/TIDS/OCEAN/hadgem3/forcing/ocean/eORCA025/ORCA025_rnficbisf_rignot2013_noberg.nc

# Source data for the rivers domain
ORCA_DOMAIN=/g/data/access/TIDS/OCEAN/hadgem3/grids/ocean/eORCA025/domcfg_eORCA025.nc

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/rivers/qrparm.rivseq

# App configuration
ANTS_CONFIG=${PWD}/rose-app-run.conf

[ants_regridding_horizontal]
scheme=Linear
