[command]
# Uses various sources to create a set of soil ancillaries.
# The MODEL_ICE_TILE is set in flow.cylc based on the LAND_MODEL.
default = python ancil_soils.py ${SOILS_SOURCE} \
	= --lct-ancillary=${LCT_SOURCE} --soils-lookup=${SOILS_LOOKUP} \
	= --ice-tile-id=${MODEL_ICE_TILE} -o=${OUTPUT} --ants-config=${ANTS_CONFIG}

[env]
# Location of the soils source file
SOILS_SOURCE=${ANCIL_PREPROC_PATH}/soils_hydrology.nc

# The land cover source, from the ancil_lct app
LCT_SOURCE=${ANCIL_TARGET_PATH}/vegetation/qrparm.veg.frac_cci

# Source for the Clapp-Hornberger lookup
SOILS_LOOKUP=${ANCIL_PREPROC_PATH}/soils_hydrology_lookup_clapp_hornberger.json

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/soils/soil_hydrology

# App configuration
ANTS_CONFIG=${PWD}/rose-app-run.conf

[ants_decomposition]
x_split=10
y_split=10
