# Top level options
[template variables=COMPUTE_PROJECT]
title="Compute project"
description="Which project to charge SUs to."
type=character

[template variables=LAND_MODEL]
title="Target land model"
description="Which land model to target for ancillary generation."
type=character
values='CABLE','JULES'

[template variables=ATMOSPHERE_ANCILLARIES]
title="Atmosphere ancillaries"
description="Whether to include atmosphere ancillaries."
type=logical
trigger=template variables=VERTICAL_DISCRETIZATION: true

[template variables=BEGIN_YEAR]
title="Start year"
description="Starting year for time dependent, non-climatological ancillaries."
type=integer

[template variables=END_YEAR]
title="End year"
description="End year (inclusive) for time dependent, non-climatological ancillaries."
type=integer

[template variables=CALENDAR]
title="Target calendar"
description="Which calendar to use."
type=character
values='360day','gregorian'

# Domain definition
[template variables=GRID_SOURCE]
title="Grid source"
description="Where to source the target grid from. Can be defined from the land cover source, a provided land sea mask, a provided set of lands fractions or an ESMF ocean mesh."
type=character
values='land_cover','land_sea_mask','ocean_mesh','land_fractions'
ns=domain
trigger=template variables=GRID_NAMELIST: 'land_cover', 'ocean_mesh'
	template variables=OCEAN_MESH: 'ocean_mesh'
	template variables=LAND_SEA_MASK: 'land_sea_mask'
	template variables=LAND_FRACTIONS: 'land_fractions', 'land_sea_mask'

[template variables=GRID_NAMELIST]
title="Grid namelist"
description="Target grid namelist to use, when using land_cover or ocean_mesh as the grid source."
type=character
ns=domain

[template variables=OCEAN_MESH]
title="Ocean mesh"
description="Target ocean mesh to use."
type=character
ns=domain

[template variables=LAND_SEA_MASK]
title="Land sea mask"
description="Land sea mask to use. Note that when using a land sea mask, land fractions are not included by default- target land fractions must be supplied if desired for atmosphere runs."
type=character
ns=domain

[template variables=LAND_FRACTIONS]
title="Land fractions"
description="Land fractions to use. When GRID_SOURCE="land_fractions", this is used as the original source of "truth" for the domain, but when GRID_SOURCE="land_sea_mask", it is copied to the workspace and used to generate the ocean mask (for sea surface ancillaries) and river ancillaries.
type=character
ns=domain

[template variables=VERTICAL_DISCRETIZATION]
title="Vertical discretization"
description="UM namelist file describing the vertical discretization for the atmosphere ancillaries."
ns=domain

[template variables=URBAN]
title="Urban"
description="Whether to include urban in the land cover conversion."
type=logical
ns=land

[template variables=CCI_YEAR]
title="CCI land cover year"
description="Which year to use for the CCI land cover source."
type=integer
ns=land

[template variables=SOIL_INITIAL_CONDITIONS]
title="Soil initial conditions"
description="Whether to include soil initial conditions."
type=logical
ns=land
trigger=template variables=SOIL_INITIAL_CONDITIONS: true

[template variables=SOIL_INIT_CONDS_METHOD]
title="Soil initial conditions generation method"
description="Which method to use for generating the soil initial conditions."
values='functional'
ns=land
