[template variables]
title="Workflow configuration"
description="Top level configuration options for the ancillary workflow."

[template_variables=COMPUTE_PROJECT]
title="Compute project"
description="Which project to charge SUs to."
type=character

[template_variables=LAND_MODEL]
title="Target land model"
description="Which land model to target for ancillary generation."
type=character
values="CABLE","JULES"

[template_variables=ATMOSPHERE_ANCILLARIES]
title="Atmosphere ancillaries"
description="Whether to include atmosphere ancillaries."
type=logical

[template_variables=SOIL_INITIAL_CONDITIONS]
title="Soil initial conditions"
description="Whether to include soil initial conditions."
type=logical

[template_variables=GRID_SOURCE]
title="Grid source"
description="Where to source the target grid from. Can be defined from the land cover source, a provided land sea mask or an ocean ESMF mesh."
type=character
values="land_cover","land_sea_mask","ocean_mesh"

[template_variables=GRID_FILE]
title="Grid file"
description="Target grid file to use. Type of file depends on the grid source; it should be a namelist for `land_cover`, a PP or NetCDF file for `land_sea_mask` and a NetCDF file for `ocean_mesh`.
type=character

[template_variables=RESOLUTION]
title="Resolution"
trigger=template_variables=GRID_FILE:ocean_mesh
description="Target resolution in n<X>e format. Only respected for the `ocean_mesh` grid source, otherwise resolution is inferred by the passed grid file."
type=character

[template_variables=VERTICAL_DISCRETIZATION]
title="Vertical discretization"
description="UM namelist file describing the vertical discretization for the atmosphere ancillaries."
trigger=template_variables=ATMOSPHERE_ANCILLARES:true

[template_variables=CALENDAR]
title="Target calendar"
description="Which calendar to use."
type=character
values="360day","gregorian"

[template_variables=URBAN]
title="Urban"
description="Whether to include urban in the land cover conversion."
type=logical

[template_variables=CCI_YEAR]
title="CCI land cover year"
description="Which year to use for the CCI land cover source."
type=integer

[template_variables=BEGIN_YEAR]
title="Start year"
description="Starting year for time dependent, non-climatological ancillaries."
type=integer

[template_variables=END_YEAR]
title="End year"
description="End year (inclusive) for time dependent, non-climatological ancillaries."
type=integer

[template_variables=SOIL_INIT_CONDS_METHOD]
title="Soil initial conditions generation method"
description="Which method to use for generating the soil initial conditions."
type=str
values="functional"
