[command]
# Regrid the reference soil albedo onto the generated land mask
default = python ancil_general_regrid.py ${ALBEDO_SOURCE} \
	= --target-lsm=${TARGET_LSM} -o=${OUTPUT} --ants-config=${ANTS_CONFIG}

[env]
# Source of the albedo data
ALBEDO_SOURCE=${ANCIL_MASTER}/atmos/master/land_clim/GlobAlbedo/v2/qrclim.land.nc

# Landmask to project onto
TARGET_LSM=${ANCIL_TARGET_PATH}/land_sea_mask/qrparm.mask.nc

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/regridded/regridded/qrclim.land

# App configuration
ANTS_CONFIG=${PWD}/rose-app-run.conf

[ants_decomposition]
x_split=10
y_split=10

[ants_regridding_horizontal]
scheme=Linear
