[command]
default=python ancil_lct.py ${LAND_COVER_SOURCE} ${GRID_SOURCE} \
       =--transform-path=${TRANSFORM_FILE} --landseamask-output=${OUTPUT_LSM_PATH} \
       =--ants-config=${ANTS_CONFIG} \
       =--ice-tile-id=${MODEL_ICE_TILE} --soil-tile-id=${MODEL_SOIL_TILE}

# Grid source is either "--target-grid=..." or "--target-lsm=...".
# The TRANSFORM_FILE, MODEL_ICE_TILE and MODEL_SOIL_TILE are set based on the model. 
# TRANSFORM FILE comes from the app options, the tile IDs come from the suite options

[env]
LAND_COVER_SOURCE=/scratch/rp23/lw5085/ESACCI-LC-L4-LCCS-Map-300m-P1Y-2015-v2.0.7b-water-fixed.nc
TARGET_GRID=/g/data/access/TIDS/UM/ancil/data/namelist/grids/grid.${resolution}/latest/grid.${resolution}
LSM_OUTPUT_PATH=${ANCIL_TARGET_PATH}
ANTS_CONFIG=ancil_lct-app.conf
