[command]
# GRID_FILE, MODEL_ICE_TILE and MODEL_SOIL_TILE are set in the main `flow.cylc`, based on
# the choices of GRID_SOURCE and LAND_MODEL in the rose-suite.conf.
default	   = echo "Something went wrong- choose a grid definition".

grid_source= mkdir -p ${LSM_OUTPUT_PATH}
       	   =
           = python ancil_lct_v1-1.py ${LAND_COVER_SOURCE} --target-grid=${GRID_FILE} \
           = --transform-path=${TRANSFORM_FILE} --landseamask-output=${LSM_OUTPUT_PATH} \
           = --ice-tile-id=${MODEL_ICE_TILE} --soil-tile-id=${MODEL_SOIL_TILE} \
           = -o=${OUTPUT} --ants-config=${ANTS_CONFIG}

lsm_source = mkdir -p ${LSM_OUTPUT_PATH}
       	   =
           = python ancil_lct_v1-1.py ${LAND_COVER_SOURCE} --target-lsm=${TARGET_LSM} \
           = --transform-path=${TRANSFORM_FILE} \
           = --ice-tile-id=${MODEL_ICE_TILE} --soil-tile-id=${MODEL_SOIL_TILE} \
           = -o=${OUTPUT} --ants-config=${ANTS_CONFIG}

[env]
# Default land cover source to use
LAND_COVER_SOURCE=/scratch/rp23/lw5085/ESACCI-LC-L4-LCCS-Map-300m-P1Y-2015-v2.0.7b-water-fixed.nc

# Default transform file, which typically lives in the ./file directory. This can be overridden for
# user defined transforms.
TRANSFORM_FILE=/scratch/rp23/lw5085/cci2cable-v5-2026-04-17.json

# Output for the vegetation fractions
OUTPUT=${ANCIL_TARGET_PATH}/vegetation/qrparm.veg.frac_cci

# The directory to write the landseamask to. The file name is fixed.
LSM_OUTPUT_PATH=${ANCIL_TARGET_PATH}/land_sea_mask/

# App configuration
ANTS_CONFIG=${PWD}/rose-app-run.conf

[ants_decomposition]
x_split=10
y_split=10
