[command]
# The preprocessing doesn't seem to depend on the resolution or land cover.
# There's no reason to be part of the suite.
default = python ancil_orography_unfiltered_preproc.py \
	= ${SOURCE} -o=${OUTPUT} --netcdf-only

[env]
# Source to use for the orography
SOURCE=${ANCIL_MASTER}/atmos/master/orography/GMTED_RAMP2/v2/qrparm.orog

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/orography/qrparm.orog_unfiltered_preproc
