[command]
# Merges the soil albedo and hydrology into a single ancillary
default = python append.py ${HYDROLOGY_SOURCE} ${ALBEDO_SOURCE} \
	= -o=${OUTPUT}

[env]
# Generated hydrology source to merge
HYDROLOGY_SOURCE=${ANCIL_TARGET_PATH}/soil/soil_hydrology.nc

# Generated albedo source to merge
ALBEDO_SOURCE=${ANCIL_TARGET_PATH}/soil/soil_albedo.nc

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/soil/qrparm.soil
