[command]
# Can also supply --netcdf-only to only write NetCDF output, and --output
# to write the output to a different name and leave the original fractions
default = apply_min_tile_fraction.py --tile-fraction=${ORIG_FRACTIONS} \
        = min_fraction=${MIN_FRACTION}

[env]
# Original tile fractions
ORIG_FRACTIONS=${ANCIL_TARGET_PATH}/vegetation/qrparm.veg.frac

# Minimum tile fraction to apply
MIN_FRACTION=0.01
