[command]
# This is an optional pre-processing step, which should only happen a new year of the
# CCI land cover is to be processed.
default = python preprocess-CCI-water.py --land-cover=${LAND_COVER_SOURCE} \
	= --water-bodies=${WATER_BODIES_SOURCE} --output=${GRID_FILE}

[env]
# Which year to use for the CCI land cover
YEAR=2015

# Resulting path for the land cover file
LAND_COVER_SOURCE=

# Source water bodies dataset
WATER_BODIES_SOURCE=
