[command]
# Regrid the aerosols onto the desired grid. VERTICAL_DISCRETIZATION is set
# in rose-suite.conf
default = cdo chname,model_level_number,level_height ${AEROSOL_SOURCE} ${TMP_AEROSOL_SOURCE}
	=
	= python ancil_general_regrid.py ${TMP_AEROSOL_SOURCE} \
	= --target-grid ${TARGET_LSM} ${VERTICAL_DISCRETIZATION} \
	= -o=${OUTPUT} --save-ukca --ants-config=${ANTS_CONFIG}
	=
	= rm ${TMP_AEROSOL_SOURCE}

[env]
# Preprocessed aerosol sources from ancil_aeroclim_preproc
AEROSOL_SOURCE=${ANCIL_TARGET_PATH}/aerosols/qrclim.pre_aerosols.nc

# Need to rename the model level dimension for ancil_general_regrid- it expects level_height
TMP_AEROSOL_SOURCE=${ANCIL_TARGET_PATH}/aerosols_tmp.nc

# Target orographic grid to project onto, from ancil_orographic_wavedrag
TARGET_LSM=${ANCIL_TARGET_PATH}/orography/qrparm.orog_wavedrag

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/qrclims.aerosols.nc

# App configuration
ANTS_CONFIG=${PWD}/rose-app-run.conf

[ants_decomposition]
x_split=10
y_split=10

[ants_regridding_vertical]
scheme=Linear

[ants_regridding_horizontal]
scheme=TwoStage
