[command]
# This doesn't depend on resolution or configuration, shouldn't be part of the suite?
default = python ancil_river_storage_preproc.py ${STORAGE_SOURCE} \
	    = -o=${OUTPUT} --netcdf-only --ants-config=${ANTS_CONFIG}

[env]
# Source data for the river storage
STORAGE_SOURCE=${ANCIL_MASTER}/atmos/master/rivers_trip/storage/fekete/v1/fekete_storage_data.pp

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/preproc/fekete_storage_data

# App configuration
ANTS_CONFIG=${PWD}/rose-app-run.conf

[ants_regridding_horizontal]
scheme=Linear
