[command]
# This doesn't depend on resolution or configuration, shouldn't be part of the suite?
default = python ancil_river_storage_preproc.py ${STORAGE_SOURCE} \
	= -o=${OUTPUT} --netcdf-only 

[env]
# Source data for the river storage
STORAGE_SOURCE=${ANCIL_MASTER}/atmos/master/rivers_trip/storage/fekete/v1/fekete_storage_data.pp

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/rivers/fekete_storage_data
