[command]
# Regrid the ozone onto the model grid. VERTICAL_DISCRETIZATION is set
# in rose-suite.conf.
default = cdo chname,model_level_number,level_height ${OZONE_SOURCE} ${OZONE_SOURCE_TMP}
	=
	= python ancil_general_regrid.py ${OZONE_SOURCE_TMP} \
	= --target-grid ${TARGET_LSM} ${VERTICAL_DISCRETIZATION} \
	= -o=${OUTPUT} --ants-config=${ANTS_CONFIG}
	=
	= rm ${OZONE_SOURCE_TMP}

[env]
# Source data for the ozone
OZONE_SOURCE=${ANCIL_MASTER}/atmos/master/ozone/CMIP5_SPARCex/1994-2005/v2/Ozone_CMIP5_SPARCex_M1994-2005_N36L70_li-ch_G.nc

# Need to rename the height dimension
OZONE_SOURCE_TMP=${ANCIL_TARGET_PATH}/ozone.nc

# Target orographic grid to project onto, from ancil_orographic_wavedrag
TARGET_LSM=${ANCIL_TARGET_PATH}/orography/qrparm.orog_wavedrag

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/ozone/qrclim_ozone

# App configuration
ANTS_CONFIG=${PWD}/rose-app-run.conf

[ants_decomposition]
x_split=1
y_split=10

[ants_regridding_horizontal]
scheme=Linear

[ants_regridding_vertical]
scheme=Linear
