[command]
# Computes the soil roughness based on the LAI
default = python ancil_soil_roughness.py ${ROUGHNESS_SOURCE} \
	= --target-lsm=${TARGET_LSM} --leaf-area-index=${LAI_SOURCE} \
	= -o=${OUTPUT} --ants-config=${ANTS_CONFIG}

[env]
# Source data to use for the roughness
ROUGHNESS_SOURCE=${ANCIL_MASTER}/atmos/master/soil_roughness/prigent12/v1/soil_roughness_preproc_prigent12.nc

# Source data to use for the LAI- not the generated LAI
LAI_SOURCE=${ANCIL_MASTER}/atmos/master/vegetation/lai/modis_4km/v2/lai_preprocessed.nc

# Landsea mask to project onto
TARGET_LSM=${ANCIL_TARGET_PATH}/qrparm.mask.nc

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/soil/qrparm.soilz0

# App configuration
ANTS_CONFIG=${PWD}/rose-app-run.conf

[ants_decomposition]
x_split=2
y_split=2

[ants_regridding_horizontal]
scheme=TwoStage
