[command]
default = python ancil_soil_albedo.py ${ALBEDO_SOURCE} \
	    = --lct-ancillary=${LCT_SOURCE} --ice-tile-id=${MODEL_ICE_TILE} \
	    = -o=${OUTPUT} --ants-config=${ANTS_CONFIG}

[env]
# Source for the soil albedo
ALBEDO_SOURCE=${ANCIL_MASTER}/atmos/master/soil_albedo/classic/v3/soil_albedo.nc

# Land cover created by ancil_lct
LCT_SOURCE=${ANCIL_TARGET_PATH}/vegetation/qrparm.veg.frac

# Where to write the output
OUTPUT=${ANCIL_TARGET_PATH}/preproc/soil_albedo

# App configuration
ANTS_CONFIG=${PWD}/rose-app-run.conf

[ants_decomposition]
x_split=10
y_split=10
